//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "PlayerTab.xaml.h"

void ::BrodcastScher::PlayerTab::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///PlayerTab.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::BrodcastScher::PlayerTab::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->btn_deviceSet = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->btn_deviceSet))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::BrodcastScher::PlayerTab::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&PlayerTab::btn_deviceSet_Click);
            }
            break;
        case 2:
            {
                this->btn_start = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->btn_start))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::BrodcastScher::PlayerTab::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&PlayerTab::btn_start_Click);
            }
            break;
        case 3:
            {
                this->btn_stop = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 4:
            {
                this->equalizerEffectContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 5:
            {
                this->eqToggle = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
            }
            break;
        case 6:
            {
                this->eq1SliderContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 7:
            {
                this->eq2SliderContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 8:
            {
                this->eq3SliderContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 9:
            {
                this->eq4SliderContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 10:
            {
                this->eq5SliderContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 11:
            {
                this->eq6SliderContainer = safe_cast<::Windows::UI::Xaml::Controls::StackPanel^>(__target);
            }
            break;
        case 12:
            {
                this->eq6Slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 13:
            {
                this->eq6SliderLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 14:
            {
                this->eq5Slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 15:
            {
                this->eq5SliderLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 16:
            {
                this->eq4Slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 17:
            {
                this->eq4SliderLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 18:
            {
                this->eq3Slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 19:
            {
                this->eq3SliderLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 20:
            {
                this->eq2Slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 21:
            {
                this->eq2SliderLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 22:
            {
                this->eq1Slider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            }
            break;
        case 23:
            {
                this->eq1SliderLabel = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::BrodcastScher::PlayerTab::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


